# Project information
site_name: Automation Test Starter
site_url: https://automation-test-starter.pages.dev//
site_author: Automation Test Starter
site_description: >-
  An organization made by QA, for QA.

  A QUICKSTART project for QA automation testing, including common test frameworks and tools, as well as some common test demo.

docs_dir: docs

nav:
- index.md
- index.zh.md
- API Automation Testing:
  - SuperTest.md
  - SuperTest.zh.md

# Repository
repo_name: Automation-Test-Starter/Organization-Docs
repo_url: https://github.com/Automation-Test-Starter/Organization-Docs

# Copyright
copyright: Copyright &copy; 2016 - 2023 Automation Test Starter

# Configuration
theme:
  name: material

extra:
  search:
    language: 'en, zh'
  i18n:
    languages:
      zh: "中文"
      en: "English"
    default_language: 'en'
  translate_nav:
    zh:
      API Automation Testing: "API自动化测试"
    en:
      API Automation Testing: "API Automation Testing"

  alternate:
    - name: "English (Home)"
      link: ""
      lang: en

    - name: "中文 (首页)"
      link: index.zh/
      lang: zh



