# Project information
site_name: Automation Test Starter
site_url: https://automation-test-starter.pages.dev/
site_author: Automation Test Starter
site_description: >-
  An organization made by QA, for QA.

  A QUICKSTART project for QA automation testing, including common test frameworks and tools, as well as some common test demo.

docs_dir: docs

nav:
- Home: index.md
- API Automation Testing:
  - SuperTest: API-Automation-Testing/SuperTest.md
  - RestAssured: API-Automation-Testing/RestAssured.md
  - Pytest: API-Automation-Testing/Pytest.md
  - Bruno: API-Automation-Testing/Bruno.md
  - Postman: API-Automation-Testing/Postman.md

- Performance Testing:
  - Performance-Testing/Gatling.md

# Repository
repo_name: Automation-Test-Starter/Organization-Docs
repo_url: https://github.com/Automation-Test-Starter/Organization-Docs

# Copyright
copyright: Copyright &copy; 2016 - 2023 Automation Test Starter

# Configuration
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs

extra:
  search:
    language: 'en, zh'
    extra:
  analytics:
    provider: google
    property: G-K091G8C97F
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.


plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true



