name: MkDocs Build and Deploy

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.x  # 选择合适的 Python 版本

  - name: Install dependencies
    run: |
      pip install mkdocs
      mkdocs --version
    # 如果你的项目依赖其他 Python 包，可以在这里安装它们

  - name: Build MkDocs site
    run: mkdocs build
    # 如果你的 MkDocs 配置文件不在根目录，使用 -f 选项指定文件路径，例如：mkdocs build -f path/to/mkdocs.yml

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: site
    # 将生成的站点部署到 GitHub Pages
